BTCPAY_CERTIFICATE_FILE_PATH = "#{Rails.root}/config/btcpay_certificate.pem"
BTCPAY_NOTIFICATION_EMAIL = ENV['BTCPAY_NOTIFICATION_EMAIL']
BTCPAY_URL = ENV['BTCPAY_URL']
BTCPAY_CERTIFICATE = File.read(BTCPAY_CERTIFICATE_FILE_PATH)
BTCPAY_MERCHANT_TOKEN = ENV['BTCPAY_MERCHANT_TOKEN']

puts 'Empty BTCPAY_NOTIFICATION_EMAIL environmental variable' if BTCPAY_NOTIFICATION_EMAIL.nil?
puts 'Empty BTCPAY_URL environmental variable' if BTCPAY_URL.nil?
puts "Empty BTCPAY_CERTIFICATE. Set it in #{BTCPAY_CERTIFICATE_FILE_PATH}" if BTCPAY_CERTIFICATE.nil?
puts 'Empty BTCPAY_MERCHANT_TOKEN environmental variable' if BTCPAY_MERCHANT_TOKEN.nil?
